config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root 'pages#dashboard', as: :subdomain_root
    get 'oportunidades/update_oportunidades', as: 'update_oportunidades'
    get '/agenda', to: 'atividades#agenda', as: 'agenda'
    devise_for :users
    resources :accounts
    resources :produtos
    resources :cliente_potencials do
      resources :oportunidades do
        #resources :atividades
      end      
      resources :contatos
      resources :enderecos
    end
    resources :atividades
  end

  constraints(SubdomainBlank) do
    root 'pages#index'
    get 'users/sign_in', to: "pages#recoversubdomain", constraints: { subdomain: '' }
    resources :accounts, only: [:new, :create]
  end
end

app/models/contato.rb
class Contato < ActiveRecord::Base
  validates :nome, presence: true
  validates :email, presence: true


  belongs_to :cliente_potencial
end

app/controllers/contatos_controller.rb
class ContatosController < ApplicationController
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  def index
    @contatos = Contato.all
  end

  def show
  end

  def new
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @contato = @cliente_potencial.contatos.build
  end

  def edit
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @contato = Contato.find(params[:id])
  end

  def create
    
    @contato = Contato.new(contato_params)
    if @contato.save
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "contatos/new"
    end  
  end

  def update
    if @contato.update(contato_params)
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "contatos/edit"
    end    
  end
  
  def destroy
    @contato.destroy
    redirect_to cliente_potencial_path(params[:cliente_potencial_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :cargo, :telefone, :celular, :email, :facebook, :linkedin, :googleplus, :cliente_potencial_id)
    end
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/views/contatos/_form.html.erb
<%= form_for([@cliente_potencial, @contato]) do |f| %>
  <% if @contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% @contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><span style="color:red;">*</span> Indica campos obrigatórios</div><br/><br/>

  <div class="form-group">
    <%= f.label :nome %>&nbsp;<span style="color:red;">*</span>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :telefone %><br>
    <%= f.text_field :telefone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :celular %><br>
    <%= f.text_field :celular, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %>&nbsp;<span style="color:red;">*</span>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :facebook %><br>
    <%= f.text_field :facebook, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :linkedin %><br>
    <%= f.text_field :linkedin, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :googleplus %><br>
    <%= f.text_field :googleplus, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :observacao, "Observações" %><br>
    <%= f.text_area :observacao, class: "form-control" %>
  </div>
  <%= f.hidden_field :cliente_potencial_id %>
  <div class="actions">
    <%= f.submit "Gravar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<div class="page-header">
	<h1>Editar Contato</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Exibir', cliente_potencial_contato_path(:cliente_potencial_id => @contato.cliente_potencial_id, :id => @contato.id) %> |
		<%= link_to 'Voltar', cliente_potencial_path(@contato.cliente_potencial_id) %>
	</div>
</div>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cargo</th>
      <th>Telefone</th>
      <th>Celular</th>
      <th>Email</th>
      <th>Facebook</th>
      <th>Linkedin</th>
      <th>Googleplus</th>
      <th>Cliente potencial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.cargo %></td>
        <td><%= contato.telefone %></td>
        <td><%= contato.celular %></td>
        <td><%= contato.email %></td>
        <td><%= contato.facebook %></td>
        <td><%= contato.linkedin %></td>
        <td><%= contato.googleplus %></td>
        <td><%= contato.cliente_potencial %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>

app/views/contatos/new.html.erb
<div class="page-header">
	<h1>Novo Contato</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Voltar', cliente_potencial_path(@cliente_potencial) %>
	</div>
</div>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @contato.nome %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Cargo:</strong><br>
          <%= @contato.cargo %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Telefone:</strong><br>
          <%= @contato.telefone %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Celular:</strong><br>
          <%= @contato.celular %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Email:</strong><br>
          <%= @contato.email %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Facebook:</strong><br>
          <%= @contato.facebook %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Linkedin:</strong><br>
          <%= @contato.linkedin %>
        </p>
      </div>  
      <div class="col-md-4">
        <p>
          <strong>Googleplus:</strong><br>
          <%= @contato.googleplus %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Observações:</strong><br>
          <%= @contato.observacao %>
        </p>
      </div>
    </div>
  </div>
</div>


<%= link_to 'Editar', edit_cliente_potencial_contato_path(:cliente_potencial_id => @contato.cliente_potencial_id, :id => @contato.id) , :class => "btn btn-primary" %> 
<%= link_to 'Voltar', cliente_potencial_path(@contato.cliente_potencial_id) , :class => "btn btn-primary" %>