config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root 'pages#dashboard', as: :subdomain_root
    get 'oportunidades/update_oportunidades', as: 'update_oportunidades'
    get '/agenda', to: 'atividades#agenda', as: 'agenda'
    devise_for :users
    resources :accounts
    resources :produtos
    resources :cliente_potencials do
      resources :oportunidades do
        #resources :atividades
      end      
      resources :contatos
      resources :enderecos
    end
    resources :atividades
  end

  constraints(SubdomainBlank) do
    root 'pages#index'
    get 'users/sign_in', to: "pages#recoversubdomain", constraints: { subdomain: '' }
    resources :accounts, only: [:new, :create]
  end
end

app/models/cliente_potencial.rb
class ClientePotencial < ActiveRecord::Base
  validates :nome, presence: true

  has_many :contatos
  has_many :oportunidades
  has_many :enderecos

  def self.searchByNome(search)
  	where("nome like ?", "%#{search}%")
  end
end

app/controllers/cliente_potencials_controller.rb
class ClientePotencialsController < ApplicationController
  before_action :set_cliente_potencial, only: [:show, :edit, :update, :destroy]

  # GET /cliente_potencials
  # GET /cliente_potencials.json
  def index
    if params[:search]
      @cliente_potencials = ClientePotencial.searchByNome(params[:search])
      @cliente_potencials = Kaminari.paginate_array(@cliente_potencials).page(params[:page]).per(5)
    else
      @cliente_potencials = ClientePotencial.page(params[:page]).per(5)
    end
  end

  # GET /cliente_potencials/1
  # GET /cliente_potencials/1.json
  def show
    @atividades = Atividade.where("cliente_potencial_id = ?", params[:id])
  end

  # GET /cliente_potencials/new
  def new
    @cliente_potencial = ClientePotencial.new
  end

  # GET /cliente_potencials/1/edit
  def edit
  end

  # POST /cliente_potencials
  # POST /cliente_potencials.json
  def create
    @cliente_potencial = ClientePotencial.new(cliente_potencial_params)

    respond_to do |format|
      if @cliente_potencial.save
        format.html { redirect_to @cliente_potencial, notice: 'Cliente potencial was successfully created.' }
        format.json { render :show, status: :created, location: @cliente_potencial }
      else
        format.html { render :new }
        format.json { render json: @cliente_potencial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cliente_potencials/1
  # PATCH/PUT /cliente_potencials/1.json
  def update
    respond_to do |format|
      if @cliente_potencial.update(cliente_potencial_params)
        format.html { redirect_to @cliente_potencial, notice: 'Cliente potencial was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente_potencial }
      else
        format.html { render :edit }
        format.json { render json: @cliente_potencial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cliente_potencials/1
  # DELETE /cliente_potencials/1.json
  def destroy
    @cliente_potencial.destroy
    respond_to do |format|
      format.html { redirect_to cliente_potencials_url, notice: 'Cliente potencial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente_potencial
      @cliente_potencial = ClientePotencial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_potencial_params
      params.require(:cliente_potencial).permit(:nome, :descricao, :website, :setor, :porte, :numero_funcionarios, :faturamento ,:observacao)
    end
end

app/helpers/cliente_potencials_helper.rb
module ClientePotencialsHelper
	def cliente_potencial_porte(porte)
		case porte
		when '1'
		  @porte = "Micro"
		when '2'
		  @porte = "Pequena"
		when '3'
		  @porte = "Média"
		when '4'
			@porte = "Média-Grande"    
		when '5'
			@porte = "Grande" 	
		end
	end

	def cliente_potencial_numero_funcionarios(numero_funcionarios)
		case numero_funcionarios
		when 1
		  @numero_funcionarios = "até 10"
		when 2
		  @numero_funcionarios = "entre 11 e 49"
		when 3
		  @numero_funcionarios = "entre 50 e 99"
		when 4
			@numero_funcionarios = "mais de 99" 	
		end
	end
end

app/views/cliente_potencials/_form.html.erb
      <%= form_for(@cliente_potencial) do |f| %>
        <% if @cliente_potencial.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@cliente_potencial.errors.count, "error") %> prohibited this cliente_potencial from being saved:</h2>

            <ul>
            <% @cliente_potencial.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div><span style="color:red;">*</span> Indica campos obrigatórios</div><br/><br/>

        <div class="form-group">
          <%= f.label :nome %>&nbsp;<span style="color:red;">*</span>
          <%= f.text_field :nome, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :descricao, "Descrição" %><br>
          <%= f.text_area :descricao, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :website %><br>
          <%= f.text_field :website, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :setor %><br>
          <%= f.text_field :setor, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :porte %><br>
          <%= f.select(:porte,
              options_for_select([['Micro', '1'], ['Pequena', '2'], ['Média', '3'], ['Média-Grande', '4'], ['Grande', '5']], @cliente_potencial.porte), {include_blank: "Selecione"}, {class: "form-control"}) %>
        </div>
         <div class="form-group">
          <%= f.label :numero_funcionarios, "Número de Funcionários" %><br>
          <%= f.select(:numero_funcionarios,
              options_for_select([['até 10', 1], ['entre 11 e 49', 2], ['entre 50 e 99', 3], ['mais de 99', 4]], @cliente_potencial.numero_funcionarios), {include_blank: "Selecione"}, {class: "form-control"}) %>
        </div>
         <div class="form-group">
          <%= f.label :faturamento %><br>
          <%= f.text_field :faturamento, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :observacao, "Observações" %><br>
          <%= f.text_area :observacao, class: "form-control" %>
        </div>
        <div class="actions">
          <%= f.submit "Gravar", class: "btn btn-primary" %>
        </div>
      <% end %>

app/views/cliente_potencials/edit.html.erb
<div class="page-header">
	<h1>Editar Cliente Potencial</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Exibir', @cliente_potencial %> |
		<%= link_to 'Voltar', cliente_potencials_path %>
	</div>
</div>

app/views/cliente_potencials/index.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1>Clientes Potenciais</h1>
</div>

<%= link_to 'Novo Cliente Potencial', new_cliente_potencial_path, :class => "btn btn-primary" %><br><br>


<%= form_tag(cliente_potencials_path, :method => "get", id: "search-form") do %>
  <div class="row">
    <div class="col-md-6">
      <div id="custom-search-input">
          <div class="input-group col-md-12">
              <%= text_field_tag :search, params[:search], placeholder: "Buscar Clientes Potenciais", class: "form-control" %>
              <span class="input-group-btn">
                  <button class="btn btn-info btn-lg" type="submit">
                      <i class="glyphicon glyphicon-search"></i>
                  </button>
              </span>
          </div>
      </div>
    </div>
  </div>

<% end %>
<br><br>

<ul class="list-group">
<% @cliente_potencials.each do |cliente_potencial| %>
    <li class="list-group-item">
      <h4 class="list-group-item-heading"><%= cliente_potencial.nome %></h4>
        <div class="list-group-item-text">


          <div class="col-md-3">
            <strong>Website:</strong>
            <%= cliente_potencial.website %>
          </div>
          <div class="col-md-2">
            <strong>Setor:</strong>
            <%= cliente_potencial.setor %>
          </div>
          <div class="col-md-2">
            <strong>Porte:</strong>
            <%= cliente_potencial_porte(cliente_potencial.porte) %>
          </div>
          <div class="col-md-3">
            <strong>Funcionários:</strong>
            <%= cliente_potencial_numero_funcionarios(cliente_potencial.numero_funcionarios) %>
          </div
          <div class="col-md-2">
            <%= link_to '', cliente_potencial, data: { no_turbolink: true, toggle: "tooltip", placement: "top" }, title: "Ver Detalhes", :class => "btn btn-primary btn-xs glyphicon glyphicon-eye-open" %></td>
            <%= link_to '', edit_cliente_potencial_path(cliente_potencial), data: {toggle: "tooltip", placement: "top" }, title: "Editar", :class => "btn btn-primary btn-xs glyphicon glyphicon-pencil" %></td>
            <%= link_to '', cliente_potencial, method: :delete, data: { confirm: 'Tem certeza?', toggle: "tooltip", placement: "top" }, title: "Excluir" , :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %>
          </div>
        
    </li>
<% end %>
</ul>
<%= paginate @cliente_potencials %>
<%= page_entries_info @cliente_potencials %>

<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip();
  })
</script>

app/views/cliente_potencials/new.html.erb
<div class="page-header">
	<h1>Novo Cliente Potencial</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Voltar', cliente_potencials_path %>
	</div>
</div>

app/views/cliente_potencials/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @cliente_potencial.nome %></h1>
</div>

<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
  <li class="active"><a href="#detalhes" data-toggle="tab">Detalhes</a></li>
  <li><a href="#oportunidades" data-toggle="tab">Oportunidades</a></li>
  <li><a href="#atividades" data-toggle="tab">Atividades</a></li>
  <li><a href="#enderecos" data-toggle="tab">Endereços</a></li>
  <li><a href="#contatos" data-toggle="tab">Contatos</a></li>
</ul>

<div id="my-tab-content" class="tab-content">

  <div class="tab-pane active" id="detalhes">
    <br><br>
    <div class="panel panel-default">
      <div class="panel-body">

        <div class="row">
          <div class="col-md-12">
            <p>
              <strong>Descrição:</strong><br>
              <%= @cliente_potencial.descricao %>
            </p>
          </div>
        </div>

        <div class="row">
          <div class="col-md-2">
            <p>
              <strong>Website:</strong><br>
              <%= @cliente_potencial.website %>
            </p>
          </div>
          <div class="col-md-2">
            <p>
              <strong>Setor:</strong><br>
              <%= @cliente_potencial.setor %>
            </p>
          </div>
          <div class="col-md-2">
            <p>
              <strong>Porte:</strong><br>
              <%= cliente_potencial_porte(@cliente_potencial.porte) %>
            </p>
          </div>
          <div class="col-md-3">
            <p>
              <strong>Número de Funcionários:</strong><br>
              <%= cliente_potencial_numero_funcionarios(@cliente_potencial.numero_funcionarios) %>
            </p>
          </div>
          <div class="col-md-3">
            <p>
              <strong>Faturamento:</strong><br>
              <%= @cliente_potencial.faturamento %>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <p>
              <strong>Observações:</strong><br>
              <%= @cliente_potencial.observacao %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div> <!-- fim detalhes -->

  <div class="tab-pane" id="oportunidades">

    <br><br>

    <%= link_to 'Incluir Oportunidade', new_cliente_potencial_oportunidade_path(@cliente_potencial), :class => "btn btn-primary" %><br><br>

    <table id="tboportunidade" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Status</th>
          <th>Etapa</th>
          <th>Receita estimada</th>
          <th>Probabilidade</th>
          <th></th>
        </tr>
      </thead>

      <tfoot>
        <tr>
          <th>Nome</th>
          <th>Status</th>
          <th>Etapa</th>
          <th>Receita estimada</th>
          <th>Probabilidade</th>
          <th></th>
        </tr>
      </tfoot>

      <tbody>
        <% @cliente_potencial.oportunidades.each do |oportunidade| %>
          <tr>
            <td><%= oportunidade.nome %></td>
            <td><%= oportunidade_status(oportunidade.status) %></td>
            <td><%= oportunidade_etapa(oportunidade.etapa) %></td>
            <td><%= oportunidade.receita_estimada %></td>
            <td><%= oportunidade_probabilidade(oportunidade.probabilidade) %></td>
            <td style="width:10%">
                <%= link_to '', cliente_potencial_oportunidade_path(:cliente_potencial_id => oportunidade.cliente_potencial_id, :id => oportunidade.id), data: {toggle: "tooltip", placement: "top" }, title: "Ver Detalhes" , :class => "btn btn-primary btn-xs glyphicon glyphicon-eye-open" %>
                <%= link_to '', edit_cliente_potencial_oportunidade_path(:cliente_potencial_id => oportunidade.cliente_potencial_id, :id => oportunidade.id), data: {toggle: "tooltip", placement: "top" }, title: "Editar" , :class => "btn btn-primary btn-xs glyphicon glyphicon-pencil" %>
                <%= link_to '', cliente_potencial_oportunidade_path(:cliente_potencial_id => oportunidade.cliente_potencial_id, :id => oportunidade.id), method: :delete, data: { confirm: 'Tem certeza?' }, data: {toggle: "tooltip", placement: "top" }, title: "Excluir" , :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %>
            </td>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- fim oportunidades -->


  <div class="tab-pane" id="atividades">

    <br><br>

    <%= link_to 'Nova Atividade', new_atividade_path, :class => "btn btn-primary" %><br><br>

    <table id="tbatividade" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Tipo</th>
          <th>Descrição</th>
          <th>Status</th>
          <th></th>
        </tr>
      </thead>

      <tfoot>
        <tr>
          <th>Nome</th>
          <th>Tipo</th>
          <th>Descrição</th>
          <th>Status</th>
          <th></th>
        </tr>
      </tfoot>

      <tbody>
        <% @atividades.each do |atividade| %>
          <tr>
            <td><%= atividade.nome %></td>
            <td><%= atividade_tipo(atividade.tipo) %></td>
            <td><%= atividade.descricao %></td>
            <td><%= atividade_status(atividade.status) %></td>
            <td style="width:10%">
              <%= link_to '', atividade, data: {toggle: "tooltip", placement: "top" }, title: "Ver Detalhes", :class => "btn btn-primary btn-xs glyphicon glyphicon-eye-open" %>
              <%= link_to '', edit_atividade_path(atividade), data: {toggle: "tooltip", placement: "top" }, title: "Editar", :class => "btn btn-primary btn-xs glyphicon glyphicon-pencil" %>
              <%= link_to '', atividade, method: :delete, data: { confirm: 'Tem certeza?', toggle: "tooltip", placement: "top" }, title: "Excluir", :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- fim atividades -->

    <div class="tab-pane" id="enderecos">

    <br><br>

    <%= link_to 'Incluir Endereço', new_cliente_potencial_endereco_path(@cliente_potencial), :class => "btn btn-primary" %><br><br>

    <table id="tbendereco" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Logradouro</th>
          <th>Bairro</th>
          <th>Cidade</th>
          <th>UF</th>
          <th>CEP</th>
          <th></th>
        </tr>
      </thead>

      <tfoot>
        <tr>
          <th>Nome</th>
          <th>Logradouro</th>
          <th>Bairro</th>
          <th>Cidade</th>
          <th>UF</th>
          <th>CEP</th>
          <th></th>
        </tr>
      </tfoot>

      <tbody>
        <% @cliente_potencial.enderecos.each do |endereco| %>
          <tr>
            <td><%= endereco.nome %></td>
            <td><%= endereco.logradouro %></td>
            <td><%= endereco.bairro %></td>
            <td><%= endereco.cidade %></td>
            <td><%= endereco.uf %></td>
            <td><%= endereco.cep %></td>
            <td style="width:10%">
              <%= link_to '', cliente_potencial_endereco_path(:cliente_potencial_id => endereco.cliente_potencial_id, :id => endereco.id), data: {toggle: "tooltip", placement: "top" }, title: "Ver Detalhes" , :class => "btn btn-primary btn-xs glyphicon glyphicon-eye-open" %>
              <%= link_to '', edit_cliente_potencial_endereco_path(:cliente_potencial_id => endereco.cliente_potencial_id, :id => endereco.id), data: {toggle: "tooltip", placement: "top" }, title: "Editar" , :class => "btn btn-primary btn-xs glyphicon glyphicon-pencil" %>
              <%= link_to '', cliente_potencial_endereco_path(:cliente_potencial_id => endereco.cliente_potencial_id, :id => endereco.id), method: :delete, data: { confirm: 'Tem certeza?', toggle: "tooltip", placement: "top" }, title: "Excluir" , :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div> <!-- fim enderecos -->

  <div class="tab-pane" id="contatos">

    <br><br>

    <%= link_to 'Incluir Contato', new_cliente_potencial_contato_path(@cliente_potencial), :class => "btn btn-primary" %><br><br>

    <table id="tbcontato" class="display" cellspacing="0" width="100%">
      <thead>
        <tr>
          <th>Nome</th>
          <th>Cargo</th>
          <th>Telefone</th>
          <th>Celular</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>

      <tfoot>
        <tr>
          <th>Nome</th>
          <th>Cargo</th>
          <th>Telefone</th>
          <th>Celular</th>
          <th>Email</th>
          <th></th>
        </tr>
      </tfoot>

      <tbody>
        <% @cliente_potencial.contatos.each do |contato| %>
          <tr>
            <td style="width:25%"><%= contato.nome %></td>
            <td><%= contato.cargo %></td>
            <td><%= contato.telefone %></td>
            <td><%= contato.celular %></td>
            <td><%= contato.email %></td>
            <td style="width:10%">
              <%= link_to '', cliente_potencial_contato_path(:cliente_potencial_id => contato.cliente_potencial_id, :id => contato.id), data: {toggle: "tooltip", placement: "top" }, title: "Ver Detalhes", :class => "btn btn-primary btn-xs glyphicon glyphicon-eye-open" %>
              <%= link_to '', edit_cliente_potencial_contato_path(:cliente_potencial_id => contato.cliente_potencial_id, :id => contato.id), data: {toggle: "tooltip", placement: "top" }, title: "Editar", :class => "btn btn-primary btn-xs glyphicon glyphicon-pencil" %>
              <%= link_to '', cliente_potencial_contato_path(:cliente_potencial_id => contato.cliente_potencial_id, :id => contato.id), method: :delete, data: { confirm: 'Tem certeza?', toggle: "tooltip", placement: "top" }, title: "Excluir", :class => "btn btn-primary btn-xs glyphicon glyphicon-trash" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- fim contatos -->
</div><!-- fim tab-content -->

<%= link_to 'Editar', edit_cliente_potencial_path(@cliente_potencial) , :class => "btn btn-primary" %>
<%= link_to 'Voltar', cliente_potencials_path , :class => "btn btn-primary" %>

<script type="text/javascript">
    $(document).ready(function() {
        $('#tabs').tab();
        $('[data-toggle="tooltip"]').tooltip();
    });
</script>