config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root 'pages#dashboard', as: :subdomain_root
    get 'oportunidades/update_oportunidades', as: 'update_oportunidades'
    get '/agenda', to: 'atividades#agenda', as: 'agenda'
    devise_for :users
    resources :accounts
    resources :produtos
    resources :cliente_potencials do
      resources :oportunidades do
        #resources :atividades
      end      
      resources :contatos
      resources :enderecos
    end
    resources :atividades
  end

  constraints(SubdomainBlank) do
    root 'pages#index'
    get 'users/sign_in', to: "pages#recoversubdomain", constraints: { subdomain: '' }
    resources :accounts, only: [:new, :create]
  end
end

app/models/endereco.rb
class Endereco < ActiveRecord::Base
  belongs_to :cliente_potencial
end

app/controllers/enderecos_controller.rb
class EnderecosController < ApplicationController
  before_action :set_endereco, only: [:show, :edit, :update, :destroy]

  def index
    @enderecos = Endereco.all
  end

  def show
  end

  def new
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @endereco = @cliente_potencial.enderecos.build
  end

  def edit
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @endereco =  Endereco.find(params[:id])
  end

  def create
    @endereco = Endereco.new(endereco_params)

    if @endereco.save
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "enderecos/new"
    end  
  end

  def update
    
    if @endereco.update(endereco_params)
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "enderecos/edit"
    end    
    
  end

  def destroy
    @endereco.destroy
    redirect_to cliente_potencial_path(params[:cliente_potencial_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_endereco
      @endereco = Endereco.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def endereco_params
      params.require(:endereco).permit(:nome, :logradouro, :complemento, :bairro, :uf, :cep, :cliente_potencial_id)
    end
end

app/helpers/enderecos_helper.rb
module EnderecosHelper
end

app/views/enderecos/_form.html.erb
<%= form_for([@cliente_potencial, @endereco]) do |f| %>
  <% if @endereco.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@endereco.errors.count, "error") %> prohibited this endereco from being saved:</h2>

      <ul>
      <% @endereco.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %><br>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :logradouro %><br>
    <%= f.text_field :logradouro, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :complemento %><br>
    <%= f.text_field :complemento, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :uf %><br>
    <%= f.text_field :uf, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :cep %><br>
    <%= f.text_field :cep, class: "form-control" %>
  </div>
  <%= f.hidden_field :cliente_potencial_id %>
  <div class="actions">
    <%= f.submit "Gravar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/enderecos/edit.html.erb
<div class="page-header">
	<h1>Editar Endereço</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Exibir', cliente_potencial_endereco_path(:cliente_potencial_id => @endereco.cliente_potencial_id, :id => @endereco.id) %> |
		<%= link_to 'Voltar', cliente_potencial_path(@endereco.cliente_potencial_id) %>
	</div>
</div>

app/views/enderecos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enderecos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Logradouro</th>
      <th>Complemento</th>
      <th>Bairro</th>
      <th>Uf</th>
      <th>Cep</th>
      <th>Cliente potencial</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enderecos.each do |endereco| %>
      <tr>
        <td><%= endereco.nome %></td>
        <td><%= endereco.logradouro %></td>
        <td><%= endereco.complemento %></td>
        <td><%= endereco.bairro %></td>
        <td><%= endereco.uf %></td>
        <td><%= endereco.cep %></td>
        <td><%= endereco.cliente_potencial %></td>
        <td><%= link_to 'Show', endereco %></td>
        <td><%= link_to 'Edit', edit_endereco_path(endereco) %></td>
        <td><%= link_to 'Destroy', endereco, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Endereco', new_endereco_path %>

app/views/enderecos/new.html.erb
<div class="page-header">
	<h1>Novo Endereço</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Voltar', cliente_potencial_path(@cliente_potencial) %>
	</div>
</div>

app/views/enderecos/show.html.erb
<div class="page-header">
  <h1><%= @endereco.cliente_potencial.nome %> - <%= @endereco.nome %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Logradouro:</strong><br>
          <%= @endereco.logradouro %>
        </p>
      </div>  
    </div>

    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Complemento:</strong><br>
          <%= @endereco.complemento %>
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col-md-3">
        <p>
          <strong>Bairro:</strong><br>
          <%= @endereco.bairro %>
        </p>
      </div>
      <div class="col-md-3">
        <p>
          <strong>Cidade:</strong><br>
          <%= @endereco.cidade %>
        </p>
      </div>
      <div class="col-md-3">
        <p>
          <strong>Uf:</strong><br>
          <%= @endereco.uf %>
        </p>
      </div>
      <div class="col-md-3">
        <p>
          <strong>Cep:</strong><br>
          <%= @endereco.cep %>
        </p>
      </div>
    </div>
  </div>
</div>



<%= link_to 'Editar', edit_cliente_potencial_endereco_path(:cliente_potencial_id => @endereco.cliente_potencial_id, :id => @endereco.id), :class => "btn btn-primary" %>
<%= link_to 'Voltar', cliente_potencial_path(@endereco.cliente_potencial_id), :class => "btn btn-primary" %>