config/routes.rb
class SubdomainPresent
  def self.matches?(request)
    request.subdomain.present?
  end
end

class SubdomainBlank
  def self.matches?(request)
    request.subdomain.blank?
  end
end

Rails.application.routes.draw do

  constraints(SubdomainPresent) do
    root 'pages#dashboard', as: :subdomain_root
    get 'oportunidades/update_oportunidades', as: 'update_oportunidades'
    get '/agenda', to: 'atividades#agenda', as: 'agenda'
    devise_for :users
    resources :accounts
    resources :produtos
    resources :cliente_potencials do
      resources :oportunidades do
        #resources :atividades
      end      
      resources :contatos
      resources :enderecos
    end
    resources :atividades
  end

  constraints(SubdomainBlank) do
    root 'pages#index'
    get 'users/sign_in', to: "pages#recoversubdomain", constraints: { subdomain: '' }
    resources :accounts, only: [:new, :create]
  end
end

app/models/oportunidade.rb
class Oportunidade < ActiveRecord::Base
  validates :nome, presence: true
  validates :descricao, presence: true
  validates :status, presence: true
  validates :receita_estimada, presence: true
  validates :probabilidade, presence: true

  belongs_to :cliente_potencial
  has_many :atividades

  belongs_to :decisor, class_name: "Contato"
  belongs_to :influenciador, class_name: "Contato"
  belongs_to :comprador, class_name: "Contato"

  accepts_nested_attributes_for :decisor
end

app/controllers/oportunidades_controller.rb
class OportunidadesController < ApplicationController
  before_action :set_oportunidade, only: [:show, :edit, :update, :destroy]

  def index
    #@oportunidades = Oportunidade.all
    redirect_to cliente_potencial_path(params[:cliente_potencial_id])
  end

  def show
    @atividades = Atividade.where("oportunidade_id = ?", params[:id])
  end

  def new
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @oportunidade = @cliente_potencial.oportunidades.build
  end

  def edit
    @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
    @oportunidade = Oportunidade.find(params[:id])
  end

  def create
    @oportunidade = Oportunidade.new(oportunidade_params)

    if @oportunidade.save
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "oportunidades/new"
    end    
  end

  def update
    if @oportunidade.update(oportunidade_params)
      redirect_to cliente_potencial_path(params[:cliente_potencial_id])
    else
      @cliente_potencial = ClientePotencial.find(params[:cliente_potencial_id])
      render "oportunidades/edit"
    end    
  end

  #Usado para carregar oportunidades de um cliente potencia via ajax
  def update_oportunidades
    @oportunidades = Oportunidade.where("cliente_potencial_id = ?", params[:cliente_potencial_id])
    
    respond_to do |format|
      format.js
    end  
  end

  def destroy
    @oportunidade.destroy

    redirect_to cliente_potencial_path(params[:cliente_potencial_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_oportunidade
      @oportunidade = Oportunidade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def oportunidade_params
      params.require(:oportunidade).permit(:nome, :descricao, :observacao, :status, :receita_estimada, :probabilidade, :cliente_potencial_id, :decisor_id, :influenciador_id, :comprador_id, :etapa)
    end
end

app/helpers/oportunidades_helper.rb
module OportunidadesHelper

	def oportunidade_status(status)
		case status
		when '1'
		  @status = "Em andamento"
		when '2'
		  @status = "Ganho"
		when '3'
		  @status = "Perdido"  
		end
	end

	def oportunidade_probabilidade(probabilidade)
		case probabilidade
		when '1'
		  @probabilidade = "Remota"
		when '2'
		  @probabilidade = "Baixa"
		when '3'
		  @probabilidade = "Grande"
		when '4'
			@probabilidade = "Quente"    
		end
	end
	
	def oportunidade_etapa(etapa)
		case etapa
		when '1'
		  @etapa = "Prospecção"
		when '2'
		  @etapa = "Qualificação"
		when '3'
		  @etapa = "Apresentação"
		when '4'
			@etapa = "Maturação"
		when '5'
			@etapa = "Negociação"
		when '6'
			@etapa = "Fechamento"
		when '7'
			@etapa = "Pós-Venda"			    
		end
	end
end

app/views/oportunidades/_form.html.erb
<%= form_for([@cliente_potencial, @oportunidade]) do |f| %>
  <% if @oportunidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@oportunidade.errors.count, "error") %> prohibited this oportunidade from being saved:</h2>

      <ul>
      <% @oportunidade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div><span style="color:red;">*</span> Indica campos obrigatórios</div><br/><br/>

  <div class="form-group">
    <%= f.label :nome, "Nome" %>&nbsp;<span style="color:red;">*</span>
    <%= f.text_field :nome, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descricao, "Descrição" %>&nbsp;<span style="color:red;">*</span>
    <%= f.text_area :descricao, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :status %>&nbsp;<span style="color:red;">*</span>
    <%= f.select(:status,
        options_for_select([['Em andamento', '1'], ['Ganho', '2'], ['Perdido', '3']], @oportunidade.status), {}, {class: "form-control"}) %>
  </div>
  <div class="form-group">
    <%= f.label :receita_estimada %>&nbsp;<span style="color:red;">*</span>
    <%= f.text_field :receita_estimada, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :probabilidade %>&nbsp;<span style="color:red;">*</span>
    <%= f.select(:probabilidade,
        options_for_select([['Remota', '1'], ['Baixa', '2'], ['Grande', '3'], ['Quente', '4']], @oportunidade.probabilidade), {}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label :decisor %>
    <%= f.collection_select :decisor_id, @cliente_potencial.contatos.all, :id, :nome, {include_blank: "Selecione"}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :influenciador %>
    <%= f.collection_select :influenciador_id, @cliente_potencial.contatos.all, :id, :nome, {include_blank: "Selecione"}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :comprador %>
    <%= f.collection_select :comprador_id, @cliente_potencial.contatos.all, :id, :nome, {include_blank: "Selecione"}, {class: "form-control"} %>
  </div>

  <div class="form-group">
    <%= f.label :etapa %>&nbsp;<span style="color:red;">*</span>
    <%= f.select(:etapa,
        options_for_select([['Prospecção', '1'], ['Qualificação', '2'], ['Apresentação', '3'], ['Maturação', '4'], ['Negociação', '5'], ['Fechamento', '6'], ['Pós-Venda', '7']], @oportunidade.etapa), {}, {class: "form-control"}) %>
  </div>

  <div class="form-group">
    <%= f.label :observacao, "Observações" %><br>
    <%= f.text_area :observacao, class: "form-control" %>
  </div>
  <%= f.hidden_field :cliente_potencial_id %>
  <div class="actions">
    <%= f.submit "Gravar", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/oportunidades/_oportunidade.html.erb
<option value="<%= oportunidade.id %>"><%= oportunidade.nome %></option>

app/views/oportunidades/edit.html.erb
<div class="page-header">
	<h1>Editar Oportunidade</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Exibir', cliente_potencial_oportunidade_path(:cliente_potencial_id => @oportunidade.cliente_potencial_id, :id => @oportunidade.id) %> |
<%= link_to 'Voltar', cliente_potencial_path(@oportunidade.cliente_potencial_id) %>

	</div>
</div>

app/views/oportunidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Oportunidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Descricao</th>
      <th>Observacao</th>
      <th>Status</th>
      <th>Receita estimada</th>
      <th>Probabilidade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @oportunidades.each do |oportunidade| %>
      <tr>
        <td><%= oportunidade.nome %></td>
        <td><%= oportunidade.descricao %></td>
        <td><%= oportunidade.observacao %></td>
        <td><%= oportunidade.status %></td>
        <td><%= oportunidade.receita_estimada %></td>
        <td><%= oportunidade.probabilidade %></td>
        <td><%= link_to 'Show', oportunidade %></td>
        <td><%= link_to 'Edit', edit_oportunidade_path(oportunidade) %></td>
        <td><%= link_to 'Destroy', oportunidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Oportunidade', new_oportunidade_path %>

app/views/oportunidades/new.html.erb
<div class="page-header">
	<h1>Nova Oportunidade</h1>
</div>

<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>

<div class="row">
	<div class="col-md-6">
		<%= link_to 'Voltar', cliente_potencial_path(@cliente_potencial) %>
	</div>
</div>

app/views/oportunidades/show.html.erb
<p id="notice"><%= notice %></p>

<div class="page-header">
  <h1><%= @oportunidade.nome %></h1>
</div>

<div class="panel panel-default">
  <div class="panel-body">
    <div class="row"></div>
    <p>
      <strong>Descrição:</strong><br>
      <%= @oportunidade.descricao %>
    </p>

    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Status:</strong><br>
          <%= oportunidade_status(@oportunidade.status) %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Receita estimada:</strong><br>
          <%= @oportunidade.receita_estimada %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Probabilidade:</strong><br>
          <%= oportunidade_probabilidade(@oportunidade.probabilidade) %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <p>
          <strong>Decisor:</strong><br>
          <% if @oportunidade.decisor != nil %>
            <%= @oportunidade.decisor.nome %>
          <% end %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Influenciador:</strong><br>
          <% if @oportunidade.influenciador != nil %>
            <%= @oportunidade.influenciador.nome %>
          <% end %>
        </p>
      </div>
      <div class="col-md-4">
        <p>
          <strong>Comprador:</strong><br>
          <% if @oportunidade.comprador != nil %>
            <%= @oportunidade.comprador.nome %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p>
          <strong>Observação:</strong><br>
          <%= @oportunidade.observacao %>
        </p>
      </div>
    </div>
  </div>
</div>




<br>

<h3>Atividades</h3>

<%= link_to 'Nova Atividade', new_atividade_path, :class => "btn btn-primary" %><br><br>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo</th>
      <th>Descrição</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @atividades.each do |atividade| %>
      <tr>
        <td><%= atividade.nome %></td>
        <td><%= atividade_tipo(atividade.tipo) %></td>
        <td><%= atividade.descricao %></td>
        <td><%= atividade_status(atividade.status) %></td>
        <td><%= link_to 'Exibir', atividade, :class => "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Editar', edit_atividade_path(atividade), :class => "btn btn-primary btn-xs" %></td>
        <td><%= link_to 'Excluir', atividade, method: :delete, data: { confirm: 'Tem certeza?' }, :class => "btn btn-primary btn-xs" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Editar', edit_cliente_potencial_oportunidade_path(:cliente_potencial_id => @oportunidade.cliente_potencial_id, :id => @oportunidade.id) , :class => "btn btn-primary" %> 
<%= link_to 'Voltar', cliente_potencial_path(@oportunidade.cliente_potencial_id) , :class => "btn btn-primary" %>